DJUNGLE-ZARATOM/evento/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^mostrar/(?P<id>[0-9]+)$', views.mostrar_evento, name='mostrar_evento'),

]

DJUNGLE-ZARATOM/eventoFCRS/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^evento/', include('evento.urls')),
]

DJUNGLE-ZARATOM/evento/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
from django.db import models

# Create your models here.
@python_2_unicode_compatible
class Evento(models.Model):
    nome = models.CharField(max_length = 200)
    data = models.DateField()
    local = models.CharField(max_length = 200)
    descricao = models.TextField(blank=True)
    horario = models.TimeField()
    vagas = models.PositiveIntegerField()
    organizador = models.CharField(max_length = 200)
    email_organizador = models.EmailField()

    def __str__(self):
        return self.nome


GENERO_CHOICES = [
    ('', 'Gênero'),
    ('MASCULINO', 'Masculino'),
    ('FEMININO', 'Feminino'),
]

ESTADOS_CHOICES = [
    ('', 'UF'),
    ('AC', 'Acre'),
    ('AL', 'Alagoas'),
    ('AP', 'Amapá'),
    ('BA', 'Bahia'),
    ('CE', 'Ceará'),
    ('DF', 'Distrito Federal'),
    ('ES', 'Espírito Santo'),
    ('GO', 'Goiás'),
    ('MA', 'Maranhão'),
    ('MG', 'Minas Gerais'),
    ('MS', 'Mato Grosso do Sul'),
    ('MT', 'Mato Grosso'),
    ('PA', 'Pará'),
    ('PB', 'Paraíba'),
    ('PE', 'Pernambuco'),
    ('PI', 'Piauí'),
    ('PR', 'Paraná'),
    ('RJ', 'Rio de Janeiro'),
    ('RN', 'Rio Grande do Norte'),
    ('RO', 'Rondônia'),
    ('RR', 'Roraima'),
    ('RS', 'Rio Grande do Sul'),
    ('SC', 'Santa Catarina'),
    ('SE', 'Sergipe'),
    ('SP', 'São Paulo'),
    ('TO', 'Tocantins')
]


@python_2_unicode_compatible
class Usuario(models.Model):
    nome = models.CharField(max_length = 200)
    email = models.EmailField()
    cpf = models.CharField(max_length = 200, unique=True)
    genero = models.CharField(max_length = 200, choices=GENERO_CHOICES)
    idade = models.PositiveIntegerField()
    telefone = models.CharField(max_length = 200)
    cidade = models.CharField(max_length = 200)
    estado = models.CharField(max_length = 200, choices=ESTADOS_CHOICES)

    def __str__(self):
        return self.nome


class Inscricao(models.Model):
    evento= models.ForeignKey(Evento, on_delete=models.SET_NULL, null=True)
    usuario= models.ForeignKey(Usuario, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.evento.nome + " - " + self.usuario.nome

DJUNGLE-ZARATOM/evento/views.py
from django.shortcuts import render
from django.http import HttpResponse
from evento.models import Evento
from django.shortcuts import get_object_or_404

def index(request):
    eventos = Evento.objects.all()
    return render(request, 'evento/home.html', {'lista_eventos':eventos})

def mostrar_evento(request, id):
    evento = get_object_or_404(Evento, id=id)
    return render(request, 'evento/mostrarEvento.html', {'evento':evento})

DJUNGLE-ZARATOM/evento/templates/evento/home.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Evento FCRS</title>

    <link href="{% static 'evento/css/bootstrap.min.css' %}" rel="stylesheet">

  </head>
  <body>
    <div class="container">

      <div class="col-md-6">
          <img src="{% static 'evento/img/imagem.png'%}" height="100" alt="" />
      </div>


      <div class="col-md-6" id="top">
        <h1> Seja Bem Vindo ao Sistema do Eventos da FCRS</h1>
      </div>


        <div class="col-md-6">
          {% for evento in lista_eventos %}
          <h3>{{evento.nome}}</h3>
          <h4>{{evento.data}} - {{evento.local}}</h4>
          <a href="{% url 'mostrar_evento' evento.id %}" class="btn btn-primary">Ir para página do evento</a>

          {% if evento.vagas > eventos.inscricao_set.all.count%}
          <a href="#" class="btn btn-success">Inscreva-se</a>
          {% else %}
          <a href="#" class="btn btn-danger">Vagas esgotadas!</a>
          {% endif %}


          {% endfor %}
        </div>



    </div>

  </body>
</html>

DJUNGLE-ZARATOM/evento/templates/evento/mostrarEvento.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{{evento.nome}}</title>
    <link href="{% static 'evento/css/bootstrap.min.css' %}" rel="stylesheet">
  </head>
  <body>

    <div class="container">

    <img src="{% static 'evento/img/imagem.png'%}" height="200" alt="" />


      <div class="col-md-6">
        <h1>{{evento.nome}}</h1>
        <h3>Data: {{evento.data}}</h3>
        <h3>Loical: {{evento.local}}</h3>
        <h3>Horário: {{evento.horario}}</h3>
        <h3>Vagas: {{evento.vagas}}</h3>
        <h3>Organizador: {{evento.organizador}}</h3>
        <h3>Email: {{evento.email_organizador}}</h3>
      </div>

      <div class="col-md-6">

        <h4>Descrição</h4>
        {{evento.descricao}}
      </div>

      <div class="col-md-12">
        <h4>Inscritos:</h4>
        <ul>
          {%for i in evento.inscricao_set.all%}
          <li>{{i.usuario.nome}}</li>
          {%endfor%}
        </ul>
      </div>

    </div>

  </body>
</html>